### ISSUE TITLE
Kubernetes 1.26

### ISSUE THREAD

**Issue by sametdoksanoglu** [evgeniy-khist/podman-testcontainers#4]
Hi,
As you know, kubernetes decide to remove docker shim starting from 1.25. We were using docker in docker image in jenkins to run docker commands in previous kubernetes versions. But after 1.25, it is not possible
I used pod below to run testcontainers tests with maven  and define environment variables 
```
kubectl apply -f - <<EOF
apiVersion: v1
kind: Pod
metadata:
 name: podman-priv
spec:
 containers:
   - name: priv
     image: quay.io/podman/stable
     args:
       - sleep
       - "1000000"
     securityContext:
       privileged: true
EOF
```
```
DOCKER_HOST="unix:///run/user/$UID/podman/podman.sock" \
TESTCONTAINERS_RYUK_DISABLED="true"
```
it gave the error _/var/run/docker.sock: no such file or directory._
 Do you think  podman can replace docker in terms of testcontainers usage in kubernetes 1.25+?
